name: Deploy Lambda Image to ECR

on:
  push:
    branches:
      - master    # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate Docker to Amazon ECR
      - name: Authenticate to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 3: Build the Docker image in the correct directory
      - name: Build Docker image
        working-directory: vilcart_streaming_code  # Set the correct folder where Dockerfile exists
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY_NAME }} .

      # Step 4: Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest

      # Step 5: Push the Docker image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest

      # Step 6: (Optional) Trigger Lambda function invocation to test
      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --payload '{"key": "value"}' \
            --cli-binary-format raw-in-base64-out \
            response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Step 7: Show the Lambda function response (optional)
      - name: Show Lambda response
        run: |
          cat response.json
