name: Deploy Lambda Image to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        working-directory: Pictures/vilcart_streaming_code_demo/vilcart_streaming_code
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          
          # Show built image
          docker images
          
          # Push the image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda function to use latest image
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:latest

      - name: Wait for Lambda update
        run: |
          aws lambda wait function-updated \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}

      - name: Test Lambda function
        run: |
          aws lambda invoke \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --payload '{"SECRETS_MANAGER_SECRET_NAME": "${{ secrets.SECRETS_MANAGER_SECRET_NAME }}"}' \
            --cli-binary-format raw-in-base64-out \
            response.json

      - name: Display Lambda response and logs
        run: |
          echo "Lambda Response:"
          cat response.json
